apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-restore
  namespace: db
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: registry.gitlab.com/localdetector/public-docker-registry/k8s-examples/mysql-data:1.0
        command: 
          - bash
          - "-c"
          - |
            mysql -uroot -pP@ssword1234_ -h${MYSQL_SERVICE_HOST} --default-character-set=utf8mb4 < /data/dump.sql
        env:
        - name: MYSQL_SERVICE_HOST
          value: mysql.db.svc.cluster.local
        - name: MYSQL_SERVICE_PORT
          value: "3306"
      restartPolicy: Never
  backoffLimit: 2
  ttlSecondsAfterFinished: 100
