FROM golang:1.19 as build_sales-api
ENV CGO_ENABLE 0
ARG BUILD_REF
COPY . /service
RUN ls -lh
WORKDIR /service
RUN go build -ldflags "-X main.build=${BUILD_REF}" -o service

FROM alpine:3.14
ARG BUILD_REF
ARG BUILD_DATE
WORKDIR /service
COPY --from=build_sales-api /service/service ./


CMD ["./service"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="sales-api" \
      org.opencontainers.image.revision="${BUILD_REF}"


