kind: ReplicationController
apiVersion: v1
metadata:
  name: redis-replica
  labels:
    app: redis
    role: replicas
spec:
  replicas: 2
  selector:
    app: redis
    role: replica
  template:
    metadata: 
      labels:
        app: redis
        role: replica
    spec:
      containers:
        - name: redis-replica
          image: mysql
          ports:  
            - name: redis-server
              containerPort: 6379
      imagePullSecrets:
        - name: harbor-secret
