apiVersion: v1
kind: secrect
metadata:
  name: gitlab-ci-token
  namespace: devops
  labels:
    app: gitlab-ci-runner
data:
  # GR1348941MrK-gqWxGorfDyskdiRh
  GITLAB_CI_TOKEN: R1IxMzQ4OTQxTXJLLWdxV3hHb3JmRHlza2RpUmgK

